name: deploy_frontend

on:
    push:
        branches: [ main ]
        paths:
            - 'frontend/**'
    
permissions:
      id-token: write
      contents: read

jobs:

  cypress-tests:
    runs-on: ubuntu-latest
    environment: cloud-resume-secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
       
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
        env:
          CYPRESS_api_url: ${{ secrets.API_URL }}

  build:
    runs-on: ubuntu-latest
    environment: cloud-resume-secrets
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name cloudresumechalleng --auth-mode key -d '$web' -s frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "resume-challenge-cdn" --name "resume-challenge-endpoint" --resource-group "cloud-resume-challenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()